### ISSUE TITLE
Download of Dataset and Model difficult 

### ISSUE THREAD

**Issue by tom-doerr** [ustcqidi/BeautyPredict#1]
Could you upload the dataset and model to a service other than Baidu? It looks like I can only download the files once I run their Windows Client software on my Linux machine.

**Comment by rguerral** [comment]
There is a Chrome extension (baidu-dl) that let you download without installing anything.

**Comment by Abraham21** [comment]
I re-uploaded the model to my Google Drive.
Here is the link to download the model: https://drive.google.com/file/d/1Yx8Iru-Epuhe4UWnYyu-4KwLfBKieg9u/view?usp=sharing

Cheers

**Comment by tom-doerr** [comment]
Thank you!

**Comment by david-lander** [comment]
Thank you. (Should be stickied or linked to in main README)

**Comment by ustcqidi** [comment]
@Abraham21 thanks
