### ISSUE TITLE
Label distribution learning model

### ISSUE THREAD

**Issue by uuacar** [ustcqidi/BeautyPredict#3]
Dear Diven, 

Below link is not working, is it possible you to share the trained model files?

https://pan.baidu.com/s/1d6jBWNxy3eXS5tz3TvCwsw

thanks
Ugur

**Comment by ustcqidi** [comment]
Here is the link to download the model: https://drive.google.com/file/d/1Yx8Iru-Epuhe4UWnYyu-4KwLfBKieg9u/view?usp=sharing
